const mongoose = require('mongoose');

const carSchema = new mongoose.Schema({
  make: String,
  model: String,
  year: Number,
  price: Number,
  mileage: Number,
  location: String,
  fuel: String,
  transmission: String,
  media: [String], // Array of Cloudinary URLs (images/videos)
  condition: String,
  description: String,
  vin: String,
  availability: {
    type: String,
    enum: ['Available', 'Sold', 'Reserved'],
    default: 'Available'
  },
  // Additional fields from frontend
  trim: String,
  bodyStyle: String,
  doors: String,
  manufactureMonth: String,
  manufactureYear: String,
  brand: String,
  noOfOwner: String,
  homeTestDrive: String,
  registrationMonth: String,
  registrationYear: String,
  insuranceValidityMonth: String,
  insuranceValidityYear: String,
  insuranceValid: String,
  insuranceType: String,
  rto: String,
  engineCapacity: String,
  bodyStyleDetails: String,
  ownerDetails: String,
  homeTestDriveDetails: String,
  kmRun: String,
  fuelTypeDetails: String,
  transmissionTypeDetails: String,
  exteriorColorDetails: String,
  interiorColorDetails: String,
  sellingPrice: String,
  status: String,
  mileageUnit: String,
  fuelType: String,
  driveType: String,
  transmissionType: String,
  engineType: String,
  exteriorColor: String,
  interiorColor: String,
  // Features (arrays)
  interior: [String],
  convenience: [String],
  safety: [String],
  exterior: [String],
  performance: [String],
  documentsAvailable: [String],
  additional: [String],
}, { timestamps: true });

module.exports = mongoose.model('Car', carSchema);
